### ISSUE TITLE
Something wrong in the bindgen process...

### ISSUE THREAD

**Issue by robitex** [jgallagher/rusqlite#235]
Hi all,
I'm attempting to compile `rusqlite` on Windows with the new bindgen process recently landed (no way to work with the legacy 0.9.5 version on Windows, for me).
I receive this OS error about a file that doesn't exist:

`error: failed to write `C:\apptrim\target\debug\.fingerprint\target_build_utils-56049cb8bbd5536b\build-script-build_script_build-56049cb8bbd5536b.json`
Caused by: Impossible to find the specified path. (os error 3)`

Checking the folder, I regularly found these two other files but nothing with the `.json` extension.
`build-script-build_script_build-56049cb8bbd5536b`
and
`dep-build-script-build_script_build-56049cb8bbd5536b`

I'm not an expert.
Actually, my goal with `rusqlite` is an initial assessment if is convenient or not translate the code of a LuaJIT script in Rust.
Thank you.
R.

**Comment by jgallagher** [comment]
rusqlite itself doesn't try to write any JSON files during the build process, so I'm not sure what the cause of this is. Could you run `cargo build -v` and post that output?

**Comment by robitex** [comment]
Certainly...
`Running C:\apptrim\target\debug\build\libsqlite3-sys-cdcd8d8e9f9d03e3\build-script-build
error: failed to run custom build command for `libsqlite3-sys v0.7.0 (https://github.com/jgallagher/rusqlite#7444f7b3)`
process didn't exit successfully: C:\apptrim\target\debug\build\libsqlite3-sys-cdcd8d8e9f9d03e3\build-script-build (exit code: 101)
--- stdout
cargo:rustc-link-lib=sqlite3

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any of \'libclang.dll\', \'clang.dll\', set the LIBCLANG_PATH environment variable to a path where one of these files can be found"', C:\bot\slave\stable-dist-rustc-win-gnu-64\build\src\libcore\result.rs:837
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

Uhm, it's seem that a library is missing...

**Comment by jgallagher** [comment]
What does

> unuseful to set SQLITE3_LIB_DIR and SQLITE3_INCLUDE_DIR

mean? I don't have a Windows system available to test on, but I know we set those environment variables for our builds on Windows CI. From [appveyor.yml](https://github.com/jgallagher/rusqlite/blob/master/appveyor.yml):

```yaml
  - ps: Start-FileDownload 'https://sqlite.org/2017/sqlite-dll-win64-x64-3160200.zip'
  - cmd: 7z e sqlite-dll-win64-x64-3160200.zip -y > nul
  - ps: Start-FileDownload 'https://sqlite.org/2017/sqlite-amalgamation-3160200.zip'
  - cmd: 7z e sqlite-amalgamation-3160200.zip -y > nul
  - SET SQLITE3_LIB_DIR=%APPVEYOR_BUILD_FOLDER%
  - SET SQLITE3_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%
```

we download both the Windows DLL and the source (to get the header), then set the env variables to point to the folder we unzipped them into. If these env variables aren't set, the build script is expecting either for `pkg-config` to work (I doubt that works on Windows?) or for the lib and header file both to be in some system path (like `/usr/include` on Linux/OS X). If there's a better way to locate the files on Windows I don't know what it is.
