### ISSUE TITLE
Readme example fails on locally cloned rusqlite

### ISSUE THREAD

**Issue by mlfaw** [jgallagher/rusqlite#412]
I'm compiling on Windows 10 with Visual Studio 2017 x64. Here's my Cargo.toml:
```toml
[package]
name = "_test"
version = "0.1.0"
authors = ["a"]
edition = "2018"

[dependencies]
rusqlite = { path = "rusqlite", features = ["bundled"] }
time = "0.1"
```
Here's what I get for terminal output:
```console
D:\_test>cargo build --release
    Updating crates.io index
   Compiling vcpkg v0.2.6
   Compiling winapi v0.3.6
   Compiling pkg-config v0.3.14
   Compiling cc v1.0.25
   Compiling libc v0.2.43
   Compiling linked-hash-map v0.4.2
   Compiling bitflags v1.0.4
   Compiling lru-cache v0.1.1
   Compiling time v0.1.40
   Compiling libsqlite3-sys v0.9.5 (D:\_test\rusqlite\libsqlite3-sys)
   Compiling rusqlite v0.14.0 (D:\_test\rusqlite)
   Compiling _test v0.1.0 (D:\_test)
error[E0308]: mismatched types
  --> src\main.rs:32:30
   |
32 |                  &[&me.name, &me.time_created, &me.data]).unwrap();
   |                              ^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found struct `time::Timespec`
   |
   = note: expected type `&std::string::String`
              found type `&time::Timespec`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `_test`.

To learn more, run the command again with --verbose.
```
